### ISSUE TITLE
Typo on package.json

### ISSUE THREAD

**Issue by wen96** [elenatorro/jsonizer#3]
Hey,

There are type error in your `package.json` `"main": "dist/jsonize.js"` it is `jsonzier`. This cause an error trying to import the package via `es6` imports: `import jsonizer from 'jsonizer' because it doesn't find the file and can't load the library.

Can you change it and release and new version?

Thanks.

**Comment by elenatorro** [comment]
Hi Rubén :)

Please, could you convert this issue into a PR? I will check it and merge it then.

Thank you :)

**Comment by wen96** [comment]
We decided to not to use the library anymore, so, I close it. Thanks
